name: Run Hatch Format

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Update apt database
        run: |
          sudo apt update
      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: 3.12
      - name: Setup venv
        run:
          ./setup-venv.sh
      - name: Check Code
        run:
          ./check-code.sh
